package snapmeal.snapmeal.global.util;

import java.util.Map;

public class ClassNameMapper {

    private static final Map<Integer, String> classIdToName = Map.ofEntries(
            Map.entry(0, "dog"),
            Map.entry(1, "person"),
            Map.entry(2, "cat"),
            Map.entry(3, "tv"),
            Map.entry(4, "car"),
            Map.entry(5, "meatballs"),
            Map.entry(6, "marinara sauce"),
            Map.entry(7, "tomato soup"),
            Map.entry(8, "chicken noodle soup"),
            Map.entry(9, "french onion soup"),
            Map.entry(10, "chicken breast"),
            Map.entry(11, "ribs"),
            Map.entry(12, "pulled pork"),
            Map.entry(13, "hamburger"),
            Map.entry(14, "cavity"),
            Map.entry(15, "가지볶음"),
            Map.entry(16, "간장게장"),
            Map.entry(17, "갈비찜"),
            Map.entry(18, "갈비탕"),
            Map.entry(19, "갈치 조림"),
            Map.entry(20, "감자전"),
            Map.entry(21, "감자조림"),
            Map.entry(22, "감자채볶음"),
            Map.entry(23, "감자탕"),
            Map.entry(24, "건새우볶음"),
            Map.entry(25, "경단"),
            Map.entry(26, "계란국"),
            Map.entry(27, "계란말이"),
            Map.entry(28, "계란찜"),
            Map.entry(29, "계란후라이"),
            Map.entry(30, "고등어 조림"),
            Map.entry(31, "고사리나물"),
            Map.entry(32, "고추볶음"),
            Map.entry(33, "고추튀김"),
            Map.entry(34, "곱창전골"),
            Map.entry(35, "김치전"),
            Map.entry(36, "김치찌개"),
            Map.entry(37, "김치찜"),
            Map.entry(38, "깻잎장아찌"),
            Map.entry(39, "꼬막무침"),
            Map.entry(40, "떡꼬치"),
            Map.entry(41, "꽁치조림"),
            Map.entry(42, "꿀떡"),
            Map.entry(43, "냉면"),
            Map.entry(44, "닭개장"),
            Map.entry(45, "양념치킨"),
            Map.entry(46, "찜닭"),
            Map.entry(47, "닭볶음탕"),
            Map.entry(48, "도토리묵 무침"),
            Map.entry(49, "동그랑땡"),
            Map.entry(50, "깍두기"),
            Map.entry(51, "시래기 된장국"),
            Map.entry(52, "된장찌개"),
            Map.entry(53, "두부김치"),
            Map.entry(54, "두부조림"),
            Map.entry(55, "떡만두국"),
            Map.entry(56, "떡볶이"),
            Map.entry(57, "만두"),
            Map.entry(58, "매운 해물찜"),
            Map.entry(59, "매운탕"),
            Map.entry(60, "메밀국수"),
            Map.entry(61, "멸치볶음"),
            Map.entry(62, "명태찌개"),
            Map.entry(63, "무생채"),
            Map.entry(64, "미역줄기볶음"),
            Map.entry(65, "송편"),
            Map.entry(66, "배추김치"),
            Map.entry(67, "백김치"),
            Map.entry(68, "비빔냉면"),
            Map.entry(69, "삼계탕"),
            Map.entry(70, "새우튀김"),
            Map.entry(71, "생선전"),
            Map.entry(72, "설렁탕"),
            Map.entry(73, "소시지볶음"),
            Map.entry(74, "수육"),
            Map.entry(75, "수제비"),
            Map.entry(76, "콩나물무침"),
            Map.entry(77, "순대"),
            Map.entry(78, "순두부찌개"),
            Map.entry(79, "식혜"),
            Map.entry(80, "애호박볶음"),
            Map.entry(81, "약과"),
            Map.entry(82, "약밥"),
            Map.entry(83, "양념게장"),
            Map.entry(84, "어묵볶음"),
            Map.entry(85, "열무국수"),
            Map.entry(86, "열무김치"),
            Map.entry(87, "오징어채볶음"),
            Map.entry(88, "오징어튀김"),
            Map.entry(89, "육개장"),
            Map.entry(90, "잔치국수"),
            Map.entry(91, "잡채"),
            Map.entry(92, "전복죽"),
            Map.entry(93, "전통 한과"),
            Map.entry(94, "제육볶음"),
            Map.entry(95, "족발"),
            Map.entry(96, "진미채볶음"),
            Map.entry(97, "짜장면"),
            Map.entry(98, "짬뽕"),
            Map.entry(99, "쫄면"),
            Map.entry(100, "추어탕"),
            Map.entry(101, "치킨"),
            Map.entry(102, "칼국수"),
            Map.entry(103, "콩국수"),
            Map.entry(104, "콩나물국"),
            Map.entry(105, "숙주나물무침"),
            Map.entry(106, "땅콩조림"),
            Map.entry(107, "파전"),
            Map.entry(108, "편육"),
            Map.entry(109, "호박전"),
            Map.entry(110, "호박죽"),
            Map.entry(111, "홍어무침"),
            Map.entry(112, "회무침")
    );

    public static String getClassName(int classId) {
        return classIdToName.getOrDefault(classId, "Unknown");
    }
}
